trigger:
  branches:
    include:
    - main
    - development
    - releases/*
  paths:
    exclude:
    - '**/*.md'
    - docs/*
pr:
  branches:
    include:
    - main
    - development
    - releases/*
  paths:
    exclude:
    - '**/*.md'
    - docs/*

stages:
- stage: Setup

  jobs:
  - job: Setup
    pool:
      vmImage: '$(vmImage)'

    steps:
    - task: DotNetCoreCLI@2
      displayName: 'Install required workloads'
      inputs:
        command: 'custom'
        custom: 'workload'
        arguments: 'install ios'

    - task: Bash@3
      displayName: Set Xcode version to $(xcodeVersion)
      inputs:
        targetType: 'inline'
        script: |
          sudo xcode-select -s /Applications/Xcode_$(xcodeVersion).app

    - task: gitversion/setup@0
      displayName: 'Setup GitVersion'
      inputs:
       versionSpec: '5.x'

- stage: Build
  condition: and(succeeded('Setup'))
  jobs:
  - job: Build
    pool:
      vmImage: '$(vmImage)'

    steps:
    - task: gitversion/execute@0
      displayName: 'Execute GitVersion'

    - task: DotNetCoreCLI@2
      displayName: 'Build'
      inputs:
        command: 'build'
        projects: '**/*.csproj'
        arguments: '-c $(buildConfiguration) -p:Version=$(GitVersion.NuGetVersion)'

    - task: DotNetCoreCLI@2
      displayName: 'Test'
      inputs:
        command: 'test'
        projects: '**/[Tt]est*.csproj'
        arguments: '-c $(buildConfiguration) --no-restore --collect "Code coverage"'

- stage: Pack
  condition: and(succeeded('Build'), not(eq(variables['build.reason'], 'PullRequest')))
  jobs:
  - job: Pack
    pool:
      vmImage: '$(vmImage)'

    steps:
    - task: DotNetCoreCLI@2
      displayName: "Nuget pack"
      inputs:
        command: "pack"
        packagesToPack: "**/*.csproj"
        nobuild: true
        packDirectory: "$(Build.ArtifactStagingDirectory)"
        versioningScheme: byEnvVar
        versionEnvVar: "GitVersion.NuGetVersion"